### ISSUE TITLE
Failed to run P2P Bandwidth Example with SmartSSD

### ISSUE THREAD

**Issue by sdudyl** [FFGGSSJJ/VitisDevelopmentResearch#1]
After software emulation and hardware emulation
I gave the command for  example:
make all TARGET=hw PLATFORM=xilinx_u2_gen3x4_xdma_gc_2_202110_1
but Failed to generate bitstream.
What is the cause of this? I hope you can give me some advice.
Thank you very much!

[23:55:13] Starting bitstream generation..
[00:00:15] Creating bitmap...
[00:01:46] Writing bitstream ./level0_i_ulp_my_rm_partial.bit...
[00:01:46] Finished 6th of 6 tasks (FPGA bitstream generation). Elapsed time: 00h 06m 32s 
[00:01:55] Run vpl: Step impl: Completed
[00:01:56] Run vpl: FINISHED. Run Status: impl Complete!
INFO: [v++ 60-1441] [00:01:56] Run run_link: Step vpl: Completed
Time (s): cpu = 00:00:26 ; elapsed = 01:01:26 . Memory (MB): peak = 2071.855 ; gain = 0.000 ; free physical = 109190 ; free virtual = 120797
INFO: [v++ 60-1443] [00:01:56] Run run_link: Step rtdgen: Started
INFO: [v++ 60-1453] Command Line: rtdgen
INFO: [v++ 60-1454] Run Directory: /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/run_link
INFO: [v++ 60-991] clock name 'blp_s_aclk_kernel_ref_clk_00' (clock ID '0') is being mapped to clock name 'DATA_CLK' in the xclbin
INFO: [v++ 60-991] clock name 'blp_s_aclk_kernel2_ref_clk_00' (clock ID '1') is being mapped to clock name 'KERNEL_CLK' in the xclbin
INFO: [v++ 60-1230] The compiler selected the following frequencies for the runtime controllable kernel clock(s) and scalable system clock(s): Kernel (DATA) clock: blp_s_aclk_kernel_ref_clk_00 = 297, Kernel (KERNEL) clock: blp_s_aclk_kernel2_ref_clk_00 = 500
INFO: [v++ 60-1453] Command Line: cf2sw -a /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/int/address_map.xml -sdsl /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/int/sdsl.dat -xclbin /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/int/xclbin_orig.xml -rtd /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/int/bandwidth.link.rtd -o /home/embed/DYL_csd/p2p_bandwidth/_x.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/link/int/bandwidth.link.xml
ERROR: [CF2SW 83-2179] Unable to resolve addressing information on axi_interconnect_0, sptag bank0.  
Either address assignment failed, or the PFM.AXI_PORT property on axi_interconnect_0 indicates a "memory" option that was set to an slave component 
and/or slave segment that are not reachable from axi_interconnect_0.  Currently instance = ddrmem_1 and segment = C0_DDR4_ADDRESS_BLOCK.  Please correct the platform design.
ERROR: [v++ 60-398] cf2sw failed
INFO: [v++ 60-1652] Cf2sw returned exit code: 255
INFO: [v++ 60-1442] [00:01:59] Run run_link: Step rtdgen: Failed
Time (s): cpu = 00:00:02 ; elapsed = 00:00:02 . Memory (MB): peak = 2071.855 ; gain = 0.000 ; free physical = 109737 ; free virtual = 121346
ERROR: [v++ 60-661] v++ link run 'run_link' failed
ERROR: [v++ 60-626] Kernel link failed to complete
ERROR: [v++ 60-703] Failed to finish linking
INFO: [v++ 60-1653] Closing dispatch client.
Makefile:131: recipe for target 'build_dir.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/bandwidth.xclbin' failed
make: *** [build_dir.hw.xilinx_u2_gen3x4_xdma_gc_2_202110_1/bandwidth.xclbin] Error 1

**Comment by FFGGSSJJ** [comment]
Hi. Sorry that this is not an official xilinx git and I may not be able to provide much help as I myself is also a learner and developer. I think your problem might fall on environment setup. You may want to post this on Xilinx community/Xilinx git issue, there will be more people to help. Thanks!

**Comment by sdudyl** [comment]
抱歉再次打扰，我想请教一下，您在按照UG1382配置完环境之后，用vitis跑vitis_accel_examples库的时候，有什么额外配置吗，还是直接跑就make hw成功了？我直接跑遇到了这个问题。makefile需要修改吗？我直接使用了vitis_accel_examples里的makefile
